server:
  port: 3344
spring:
  application:
    name: microservicecloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LJIDWSYAM/microservicecloud-config.git
          username: LJIDWSYAM
          password: WHNABQ1980621312